name: Build

on:
  push:
    branches:
      - main  # Change this to your main branch if it's different
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up CMake
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake
        # Install Eigen3 manually
        wget https://gitlab.com/libeigen/eigen/-/archive/3.4.0/eigen-3.4.0.tar.gz
        tar xzf eigen-3.4.0.tar.gz
        cd eigen-3.4.0
        mkdir build && cd build
        cmake .. && make && sudo make install
        cd ../..
        ./scripts/install_deps.sh


    - name: Create build directory
      run: |
        mkdir build
        cd build

    - name: Configure CMake
      run: |
        cmake . -DCMAKE_BUILD_TYPE=RelWithDebInfo

    - name: Build project
      run: |
        make -j8
