name: Build

on:
  push:
    branches:
      - main  # Change this to your main branch if it's different
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clone repo
      run: |
        git clone --recursive https://gitlab.com/VladyslavUsenko/basalt.git

    - name: Set up CMake
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake

    - name: Install dependencies
      run: |
        cd basalt
        ./scripts/install_deps.sh

    - name: Create build directory
      run: |
        mkdir build
        cd build

    - name: Configure CMake
      run: |
        cmake . -DCMAKE_BUILD_TYPE=RelWithDebInfo

    - name: Build project
      run: |
        make -j8
